{
 "title": "dotnet-monitor Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "systemruntime_gc_heap_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "GC Heap Size({{pod}})"
    },
    {
     "expr": "systemruntime_working_set_bytes{instance=~\"$instance\"}",
     "legendFormat": "Working Set({{pod}})"
    }
   ]
  },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Gen 0 Size ({{pod}})"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Gen 1 Size ({{pod}})"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Gen 2 Size ({{pod}})"
    },
    {
     "expr": "systemruntime_loh_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "LOH Size ({{pod}})"
    },
    {
     "expr": "systemruntime_poh_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "POH Size ({{pod}})"
    }
   ]
  },
  {
   "title": "Monitor Lock Contention Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "systemruntime_monitor_lock_contention_count{instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_gc_count{instance=~\"$instance\"}",
     "legendFormat": "Gen 0 ({{pod}}) "
    },
    {
     "expr": "systemruntime_gen_1_gc_count{instance=~\"$instance\"}",
     "legendFormat": "Gen 1 ({{pod}}) "
    },
    {
     "expr": "systemruntime_gen_2_gc_count{instance=~\"$instance\"}",
     "legendFormat": "Gen 2 ({{pod}}) "
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{instance=~\"$instance\"}",
     "legendFormat": "Total Fragmentation ({{pod}})"
    }
   ]
  },
  {
   "title": ".NET Threadpool Completed Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_completed_items_count{instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "CPU Usage ({{pod}})"
    }
   ]
  },
  {
   "title": "ThreadPool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_queue_length{instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}